sudo: required

language: python

python:
  - "2.7"

services:
  - docker

before_install:
  - git clone -b cap-pycodestyle git://github.com/jburel/omero-test-infra .omero

script:
  - .omero/docker app
